version: '3'
services:
    config-server:
        build: ./config-scraper
        container_name: config-scraper
        working_dir: /config-scraper
        volumes:
            - ./config-scraper:/config-scraper
            - ~/.m2:/root/.m2
        networks:
            - cloud-native-network
        expose:
            - 8888
        ports:
            - "8888:8888/tcp"
            - "8888:8888/udp"
        command: mvn clean spring-boot:run
        restart: always
    eureka-scraper-server:
        build: ./eureka-scraper-server
        working_dir: /eureka-scraper-server
        volumes:
            - ./eureka-scraper-server:/eureka-scraper-server
            - ~/.m2:/root/.m2
        networks:
            - cloud-native-network
        expose:
            - 8761
        ports:
            - 8761:8761
        command: mvn clean spring-boot:run
        restart: always
        depends_on:
            - config-server
    batch-scraper:
        build: ./batch-scraper
        working_dir: /batch-scraper
        volumes:
            - ./batch-scraper:/batch-scraper
            - ~/.m2:/root/.m2
        networks:
            - cloud-native-network
        expose:
            - 8081
        ports:
            - 8081:8081
        command: mvn clean spring-boot:run
        restart: always
        depends_on:
            - config-server
    checkout-rest-scraper:
        build: ./checkout-rest-scraper
        working_dir: /checkout-rest-scraper
        volumes:
            - ./checkout-rest-scraper:/checkout-rest-scraper
            - ~/.m2:/root/.m2
        networks:
            - cloud-native-network
        expose:
            - 8082
            - 443
            - 80
        ports:
            - 8082:8082
            - 80:80
            - 443:443
        command: mvn clean spring-boot:run
        restart: always
        depends_on:
            - config-server
networks:
    cloud-native-network: