server:
  port: 8082
spring:
  application:
    name: checkout-rest-scraper
  cloud:
    config:
      enabled: true
      uri: http://config-server:8888
      name: scraperhtml-prop
      profile: dev
      label: main
    loadbalancer:
      ribbon:
        enabled: false
  health:
    config:
      enabled: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:checkoutdb
    username: sa
    password: sa
    jpa: database-platform:org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        path: /h2-console
    data:
      jpa:
        repositories:
          bootstrap-mode: default
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-scraper-server:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
checkout:
  message:
    ok: started successfully
    ko: error on start
bot:
  token: 1411635735:AAE2x8idSqoFl2-w1EhU5KutXlpgw2j_89E
  username: g433602999