spring:
  batch:
    job:
      enabled: false
  datasource:
    url: jdbc:h2:mem:batchdb
    username: sa
    password: sa
  jpa: database-platform:org.hibernate.dialect.H2Dialect
server:
  port: 8081
scraping:
  message:
    ok: started successfully
    ko: error on start