spring:
  application:
    name: eureka-scraper-server
  cloud:
    config:
      uri: http://localhost:8888
    loadbalancer:
      ribbon:
        enabled=false:
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
